QuickBootstrap/Controllers/UserManageController.cs
using System;
using System.Web.Mvc;
using QuickBootstrap.Entities;
using QuickBootstrap.Extendsions;
using QuickBootstrap.Filters;
using QuickBootstrap.Models;
using QuickBootstrap.Services;
using QuickBootstrap.Services.Impl;
using QuickBootstrap.Services.Util;

namespace QuickBootstrap.Controllers
{
    [UserAuthorization]
    public class UserManageController : Controller
    {
        #region 私有字段

        private readonly IUserManageService _userManageService = new UserManageService();

        #endregion

        #region action method

        public ActionResult Index(int pageIndex = 0, int pageSize = 20)
        {
            var paging = new Paging { PageIndex = pageIndex, PageSize = pageSize };
            return View(_userManageService.GetList(paging));
        }

        public ActionResult Create()
        {
            var viewModel = new UserCreateRequest {IsEnable = true};

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Create(UserCreateRequest model)
        {
            if (ModelState.IsValid == false)
            {
                return View(model);
            }

            if (_userManageService.ExistsUser(model.UserName) == false)
            {
                _userManageService.Create(new User
                {
                    UserName = model.UserName,
                    UserPwd = model.Password.ToMd5(),
                    Nick = model.Nick,
                    CreateTime = DateTime.Now,
                    IsEnable = model.IsEnable
                });

                return RedirectToAction("Index");
            }

            ModelState.AddModelError("_error", "登录账号已存在");

            return View(model);
        }

        public ActionResult Delete(string username = "")
        {
            if (username.Length > 0)
            {
                _userManageService.Delete(username);
            }

            return RedirectToAction("Index");
        }

        #endregion
    }
}

QuickBootstrap/Views/UserManage/Create.cshtml
@model QuickBootstrap.Models.UserCreateRequest
@{
    ViewBag.Title = "添加用户";
}

<div class="row">

    <div class="col-md-2">
        @Html.Partial("Shared/_QuickMenu")
    </div>

    <div class="col-md-10 ">

        <ol class="breadcrumb">
            <li><a href="/">管理后台</a></li>
            <li><a href="/UserManage">用户</a></li>
            <li class="active">新建用户</li>
        </ol>

        <div class="container">

            @using (Html.BeginForm("Create", "UserManage", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <div class="form-group">
                    @Html.LabelFor(model => model.UserName, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.UserName, new { @class = "form-control", style = "width: 280px", placeholder = "邮箱地址" })
                        @Html.ValidationMessageFor(model => model.UserName)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Nick, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Nick, new { @class = "form-control", style = "width: 280px", placeholder = "账号昵称" })
                        @Html.ValidationMessageFor(model => model.Nick)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Password, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(model => model.Password, new { @class = "form-control", style = "width: 280px", placeholder = "账号密码" })
                        @Html.ValidationMessageFor(model => model.Password)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsEnable, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.CheckBoxFor(model => model.IsEnable, new { @class = "form-control", style = "width: 280px" })
                        @Html.ValidationMessageFor(model => model.IsEnable)
                        <span>注：选中"启用"，不选中"禁止登陆"。</span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @Html.ValidationSummary(false)
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="submit" class="btn btn-primary">创建</button>
                        <a href="/UserManage" class="btn btn-default">取消</a>
                    </div>
                </div>
            }

        </div>
    </div>
</div>

QuickBootstrap/Views/UserManage/Index.cshtml
@model QuickBootstrap.Services.Util.PagedResult<QuickBootstrap.Services.Models.UserManagePageItem>
@{
    ViewBag.Title = "用户管理";
}

<div class="row">

    <div class="col-md-2">
        @Html.Partial("Shared/_QuickMenu")
    </div>

    <div class="col-md-10 ">

        <ol class="breadcrumb">
            <li><a href="/">管理后台</a></li>
            <li><a href="/UserManage">用户管理</a></li>
            <li class="active">
                <label class="label label-success">共查询到 @Model.SizeCount 条信息</label>
            </li>
        </ol>

        <form action="/Test/Query" method="POST">
            <div class="callout callout-info">
                <table>
                    <tr style="line-height: 42px;">
                        <td style="padding: 0 5px;">开始时间：</td>
                        <td style="padding: 0 5px;"><input type="text" class="form-control" name="StartTime"></td>
                        <td style="padding: 0 5px;">结束时间：</td>
                        <td style="padding: 0 5px;"><input type="text" class="form-control" name="EndTime"></td>
                    </tr>
                    <tr style="line-height: 42px;">
                        <td style="padding: 0 5px;">用户账号：</td>
                        <td style="padding: 0 5px;"><input type="text" class="form-control"></td>
                        <td style="padding: 0 5px;">用户角色：</td>
                        <td style="padding: 0 5px;"><input type="text" class="form-control"></td>
                    </tr>
                </table>
            </div>

            <div class="callout callout-primary">
                <div class="btn-group">
                    <button type="submit" class="btn btn-default btn-group-lg" name="Event" value="Query">查询</button>
                    <button type="submit" class="btn btn-default btn-group-lg" name="Event" value="Create">添加</button>
                    <button type="submit" class="btn btn-default btn-group-lg">修改</button>
                    <button type="submit" class="btn btn-default btn-group-lg">删除</button>
                    <button type="submit" class="btn btn-default btn-group-lg">导出</button>
                    <button type="submit" class="btn btn-default btn-group-lg">导入</button>
                    <button type="submit" class="btn btn-default btn-group-lg">打印</button>
                </div>
            </div>

        </form>

        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>序号</th>
                    <th>邮箱地址</th>
                    <th>真实姓名</th>
                    <th>账号状态</th>
                    <th>创建时间</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                @for (var i = 0; i < Model.Result.Count; i++)
                {
                    <tr>
                        <td>@(i + 1)</td>
                        <td>@Model.Result[i].UserName </td>
                        <td>@Model.Result[i].Nick </td>
                        <td>@Html.Raw(Model.Result[i].IsEnable ? "正常" : "<span class='label label-danger'>禁用</span>")</td>
                        <td>@Model.Result[i].CreateTime </td>
                        <td>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default">更多操作</button>
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                    <span class="caret"></span>
                                    <span class="sr-only"></span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="/UserManage/delete?username=@Model.Result[i].UserName">删除</a></li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        @Html.Partial("_PartialPagingInfo")

    </div>
</div>